name: SureFooting
main: com.nohupgaming.minecraft.SureFooting
version: 1.1
description: While active, safely walk on air
author: Nohup
commands:
  surefeet:
    description: Toggle surefeet status
    usage: /<command>
changelog:
  - v1.1  Added support to move platform down when looking down
  - v1.0  Initial release  
